/**
 * Type Definitions for Travel Itinerary Generator
 *
 * This file contains all TypeScript interfaces and types used throughout the application.
 * These types ensure type safety and provide autocomplete/IntelliSense support.
 */

/**
 * Geographic coordinates (latitude and longitude)
 *
 * Used for:
 * - Storing city center location
 * - Storing activity/location coordinates
 * - Displaying markers on the map
 *
 * @example
 * const nyc: Coordinates = { lat: 40.7128, lng: -74.0060 };
 */
export interface Coordinates {
  /** Latitude in decimal degrees (-90 to 90) */
  lat: number;

  /** Longitude in decimal degrees (-180 to 180) */
  lng: number;
}

/**
 * Single activity or location within a day itinerary
 *
 * Represents one stop in the user's day plan, including timing,
 * location details, and cost information.
 *
 * Generated by OpenAI and displayed in the itinerary timeline.
 *
 * @example
 * const activity: ItineraryItem = {
 *   name: "Metropolitan Museum of Art",
 *   address: "1000 5th Ave, New York, NY 10028",
 *   time: "9:00 AM - 11:00 AM",
 *   duration: "2 hours",
 *   description: "Explore world-class art collections...",
 *   type: "Museums",
 *   coordinates: { lat: 40.7794, lng: -73.9632 },
 *   travelTime: "15 min walk",
 *   estimatedCost: 30
 * };
 */
export interface ItineraryItem {
  /** Name of the activity/location (e.g., "Central Park") */
  name: string;

  /** Full street address for the location */
  address: string;

  /** Time slot in format "HH:MM AM - HH:MM AM" (e.g., "9:00 AM - 10:30 AM") */
  time: string;

  /** Human-readable duration (e.g., "1.5 hours" or "2 hours") */
  duration: string;

  /** Brief description of what to do at this location (1-2 sentences) */
  description: string;

  /** Activity type/category (must match one of ActivityType values) */
  type: string;

  /** Geographic coordinates for map display */
  coordinates: Coordinates;

  /**
   * Travel time from previous location (optional)
   *
   * Examples: "15 min walk", "10 min drive", "20 min metro"
   * First activity uses "Start of day" or omits this field
   */
  travelTime?: string;

  /**
   * Estimated cost per person in USD (optional)
   *
   * - Use 0 for free activities (parks, walking tours, etc.)
   * - Include admission fees, meal costs, etc.
   * - Displayed as "$X.XX/person" or "Free"
   */
  estimatedCost?: number;
}

/**
 * Complete itinerary with budget information
 *
 * Contains the full day plan with all activities, costs, and budget tracking.
 * Returned from the API and displayed in the results view.
 *
 * @example
 * const itinerary: Itinerary = {
 *   city: "New York",
 *   itinerary: [activity1, activity2, ...],
 *   totalCost: 180.00,        // For 2 travelers
 *   budgetRemaining: 20.00    // $200 budget - $180 spent
 * };
 */
export interface Itinerary {
  /** City name for the itinerary */
  city: string;

  /** Array of activities/locations in chronological order */
  itinerary: ItineraryItem[];

  /**
   * Total estimated cost for all travelers (optional)
   *
   * Calculated client-side: sum(estimatedCost) * travelers
   * Only present if budget and travelers were specified
   */
  totalCost?: number;

  /**
   * Remaining budget after all activities (optional)
   *
   * Calculated client-side: budget - totalCost
   * Only present if budget and travelers were specified
   * Can be negative if over budget
   */
  budgetRemaining?: number;
}

/**
 * Request body for POST /api/generate-itinerary
 *
 * Contains all user inputs needed to generate a personalized itinerary.
 *
 * @example
 * const request: GenerateItineraryRequest = {
 *   city: "New York, New York, United States",
 *   radius: "5",
 *   preferences: ["Museums", "Restaurants", "Parks & Outdoors"],
 *   coordinates: { lat: 40.7128, lng: -74.0060 },
 *   budget: 200,
 *   travelers: 2
 * };
 */
export interface GenerateItineraryRequest {
  /** Full city name from Nominatim autocomplete */
  city: string;

  /** Search radius in miles ("2", "5", "10", or "20") */
  radius: string;

  /** Array of selected activity types (min 1 required) */
  preferences: string[];

  /**
   * City center coordinates (optional)
   *
   * Obtained from Nominatim API when user selects city
   * Used to ensure activities are within radius
   */
  coordinates?: Coordinates;

  /**
   * Total budget for all travelers in USD (optional)
   *
   * Used to constrain AI recommendations
   * Divided by travelers to get per-person budget
   */
  budget?: number;

  /**
   * Number of travelers (optional)
   *
   * Defaults to 1 if not specified
   * Used to calculate total costs and per-person budget
   * Range: 1-20
   */
  travelers?: number;
}

/**
 * Result from OpenStreetMap Nominatim geocoding API
 *
 * Returned when searching for cities in the autocomplete dropdown.
 * See: https://nominatim.openstreetmap.org/
 *
 * @example
 * // API response for "New York"
 * const result: NominatimResult = {
 *   place_id: 297618410,
 *   lat: "40.7127281",
 *   lon: "-74.0060152",
 *   display_name: "New York, New York, United States",
 *   // ... other fields
 * };
 */
export interface NominatimResult {
  /** Unique identifier for this place */
  place_id: number;

  /** OpenStreetMap license information */
  licence: string;

  /** Type of OSM object ("node", "way", or "relation") */
  osm_type: string;

  /** OpenStreetMap object ID */
  osm_id: number;

  /** Latitude as string (must be parsed to number) */
  lat: string;

  /** Longitude as string (must be parsed to number) */
  lon: string;

  /** OSM class (e.g., "boundary", "place") */
  class: string;

  /** OSM type (e.g., "administrative", "city") */
  type: string;

  /** Ranking of place importance (lower = more important) */
  place_rank: number;

  /** Calculated importance score (0.0 to 1.0) */
  importance: number;

  /** Type of address (e.g., "city", "town", "village") */
  addresstype: string;

  /** Short name of the place (e.g., "New York") */
  name: string;

  /** Full formatted address (displayed in autocomplete) */
  display_name: string;

  /** Bounding box [min_lat, max_lat, min_lon, max_lon] */
  boundingbox: [string, string, string, string];
}

/**
 * Activity type categories
 *
 * All possible activity types selectable in the form.
 * Each type has associated color coding in the UI.
 *
 * To add new types:
 * 1. Add to this union type
 * 2. Add to ACTIVITY_TYPES array below
 * 3. Add color mapping in ItineraryDisplay.tsx
 * 4. Add color mapping in MapView.tsx
 */
export type ActivityType =
  | 'Restaurants'
  | 'Museums'
  | 'Parks & Outdoors'
  | 'Nightlife & Bars'
  | 'Shopping'
  | 'Historical Sites'
  | 'Entertainment'
  | 'Coffee Shops'
  | 'Art Galleries'
  | 'Sports & Recreation';

/**
 * Array of all activity types for form rendering
 *
 * Used to generate checkboxes in ItineraryForm.
 * Order determines display order in the UI.
 */
export const ACTIVITY_TYPES: ActivityType[] = [
  'Restaurants',
  'Museums',
  'Parks & Outdoors',
  'Nightlife & Bars',
  'Shopping',
  'Historical Sites',
  'Entertainment',
  'Coffee Shops',
  'Art Galleries',
  'Sports & Recreation',
];

/**
 * Available search radius options
 *
 * Defines how far from city center to look for activities.
 * Used to populate the radius dropdown in ItineraryForm.
 *
 * Smaller radius = more walkable itinerary
 * Larger radius = more driving/transit required
 */
export const RADIUS_OPTIONS = [
  { value: '2', label: 'Within 2 miles' },
  { value: '5', label: 'Within 5 miles' },
  { value: '10', label: 'Within 10 miles' },
  { value: '20', label: 'Within 20 miles' },
];

/**
 * Google Places API Integration Types
 *
 * These types represent data from Google Places API used to enrich
 * itinerary items with real reviews, ratings, photos, and other details.
 */

/**
 * Individual review from Google Places
 *
 * Contains user-generated review data including rating, text, and author info.
 *
 * @example
 * const review: GoogleReview = {
 *   author_name: "Sarah Johnson",
 *   rating: 5,
 *   text: "Amazing museum with incredible exhibits!",
 *   time: 1703001600,
 *   relative_time_description: "2 weeks ago"
 * };
 */
export interface GoogleReview {
  /** Name of the review author */
  author_name: string;

  /** Google Maps profile URL of the author (optional) */
  author_url?: string;

  /** URL to author's profile photo (optional) */
  profile_photo_url?: string;

  /** Star rating given by the reviewer (1-5) */
  rating: number;

  /** Full text of the review */
  text: string;

  /** Unix timestamp when review was posted */
  time: number;

  /** Human-readable time description (e.g., "2 weeks ago") */
  relative_time_description?: string;
}

/**
 * Photo reference from Google Places
 *
 * Contains reference to a photo that can be fetched via Google Places Photo API.
 * Use photo_reference to construct photo URL.
 *
 * @example
 * // Construct photo URL:
 * const photoUrl = `https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=${photo.photo_reference}&key=${apiKey}`;
 */
export interface GooglePlacePhoto {
  /** Reference string used to fetch the actual photo */
  photo_reference: string;

  /** Original photo height in pixels */
  height: number;

  /** Original photo width in pixels */
  width: number;

  /** HTML attributions for the photo (optional) */
  html_attributions?: string[];
}

/**
 * Complete Google Places data for a location
 *
 * Contains all enriched data from Google Places API including
 * ratings, reviews, photos, pricing, and operational details.
 *
 * @example
 * const placeData: GooglePlaceData = {
 *   place_id: "ChIJKxDbe_lYwokRVf__s8CPn-o",
 *   rating: 4.6,
 *   user_ratings_total: 12543,
 *   reviews: [...],
 *   photos: [...],
 *   price_level: 3,
 *   opening_hours: { open_now: true },
 *   website: "https://www.metmuseum.org"
 * };
 */
export interface GooglePlaceData {
  /** Unique Google Places identifier */
  place_id: string;

  /** Average star rating (1-5) */
  rating?: number;

  /** Total number of user ratings/reviews */
  user_ratings_total?: number;

  /** Array of reviews (up to 5 most recent/relevant) */
  reviews?: GoogleReview[];

  /** Array of photo references */
  photos?: GooglePlacePhoto[];

  /**
   * Price level indicator (0-4)
   *
   * - 0: Free
   * - 1: $ (Inexpensive)
   * - 2: $$ (Moderate)
   * - 3: $$$ (Expensive)
   * - 4: $$$$ (Very Expensive)
   */
  price_level?: number;

  /** Opening hours information */
  opening_hours?: {
    /** Whether the place is currently open */
    open_now: boolean;

    /** Array of opening hours for each day of the week (optional) */
    weekday_text?: string[];
  };

  /** Formatted phone number (e.g., "(212) 535-7710") */
  formatted_phone_number?: string;

  /** Website URL for the place */
  website?: string;

  /** Google-formatted full address */
  formatted_address?: string;
}

/**
 * Request body for POST /api/enrich-place
 *
 * Used to fetch Google Places data for a specific activity.
 *
 * @example
 * const request: EnrichPlaceRequest = {
 *   name: "Metropolitan Museum of Art",
 *   address: "1000 5th Ave, New York, NY 10028",
 *   city: "New York"
 * };
 */
export interface EnrichPlaceRequest {
  /** Name of the place/activity */
  name: string;

  /** Address from the itinerary */
  address: string;

  /** City name for search context */
  city: string;

  /** Optional coordinates to improve search accuracy */
  coordinates?: Coordinates;
}

/**
 * Extended itinerary item with Google Places data
 *
 * Includes all original itinerary fields plus optional Google data
 * and loading/error states for progressive enhancement.
 */
export interface EnrichedItineraryItem extends ItineraryItem {
  /** Google Places data (if successfully fetched) */
  googleData?: GooglePlaceData;

  /** Loading state for Google data fetch */
  googleLoading?: boolean;

  /** Error message if Google data fetch failed */
  googleError?: string;
}
